### ISSUE TITLE
Tapping on a post opens the wrong one

### ISSUE THREAD

**Issue by shrugal** [dessalines/jerboa#1021]
**Jerboa Version**
0.0.39

**Android version + phone**
Pixel 4, Android 13

**Describe the bug**
When going through my feed tapping on a post sometimes opens a different one from higher up in the list. It also seems to prefer posts I opened and closed a few seconds before, but I'm not 100% sure on that.

Closing the wrong post and tapping on the desired one again always opens the correct one.

**To Reproduce**

1. Scroll through feed
2. Tap on a post
3. A post from higher up in the list is opened instead
4. Close wrong post
5. Tap on desired post again
6. The correct post is opened

**Comment by MV-GH** [comment]
Yes, I have been experiencing this too. I think this is due to a recomposition reusing a older clickhandler. I took a look at the changes, and if this only has been happening since 0.39. Then maybe it is caused by #767 . If not then maybe #1002 , all though i have experienced without hitting the preview section.

**Comment by bleach86** [comment]
I am experiencing the same issue with 0.0.39 as well. I'm using the f-droid build on Pixel 6 pro on android 13.
