### ISSUE TITLE
Comment cannot be sent and there's no feedback as to why that is

### ISSUE THREAD

**Issue by Atulin** [dessalines/jerboa#1057]
### Jerboa Version

0.0.4

### Android Version + Phone

Android 11, Samsung Galaxy A50

### Describe The Bug

Trying to add a comment and failing doesn't show any feedback saying why that is the case. 

I'd expect to see a message saying "you can't leave the comment because the user blocked you" or "the instance you're trying to comment on defederate your instance" or anything of the sort. 

https://github.com/dessalines/jerboa/assets/11233299/5c0535af-bfda-4e55-901f-2ff41cc9d2ed

### To Reproduce

1. Try to comment
2. Fail
3. Wonder why

**Comment by MV-GH** [comment]
Please include the logs

**Comment by MV-GH** [comment]
Regarding the "remove account" maybe related #1053. Logs would easily confirm this

**Comment by Atulin** [comment]
I executed the ADB command, but it doesn't seem like it's doing anything. I had to `Ctrl+C` from both sessions because there was no output. One session lasted over half an hour and started from Jerboa being closed, the other stared with Jerboa being open.

```
~ via  v20.0.0 via 🐍
❯ adb shell logcat *:V --pid $(adb shell "timeout 5s logcat | sed -En 's/.*proc ([0-9]*):com.jerboa.*/\1/p' | tail -1")
--------- beginning of system
07-18 21:10:28.329 10978 10978 D ActivityThread: handleBindApplication()++ app=com.jerboa
07-18 21:10:28.379 10978 10978 D LoadedApk: LoadedApk::makeApplication() appContext=android.app.ContextImpl@9a18528 appContext.mOpPackageName=com.jerboa appContext.mBasePackageName=com.jerboa appContext.mPackageInfo=android.app.LoadedApk@5481241
07-18 21:10:28.480 10978 10978 D ActivityThread: handleBindApplication() -- skipGraphicsSupport=false


~ via  v20.0.0 via 🐍 took 35m28s
❯ adb shell logcat *:V --pid $(adb shell "timeout 5s logcat | sed -En 's/.*proc ([0-9]*):com.jerboa.*/\1/p' | tail -1")
--------- beginning of system
07-18 21:10:28.329 10978 10978 D ActivityThread: handleBindApplication()++ app=com.jerboa
07-18 21:10:28.379 10978 10978 D LoadedApk: LoadedApk::makeApplication() appContext=android.app.ContextImpl@9a18528 appContext.mOpPackageName=com.jerboa appContext.mBasePackageName=com.jerboa appContext.mPackageInfo=android.app.LoadedApk@5481241
07-18 21:10:28.480 10978 10978 D ActivityThread: handleBindApplication() -- skipGraphicsSupport=false

~ via  v20.0.0 via 🐍 took 2m42s
```

**Comment by MV-GH** [comment]
The command only shows the logs of the latest execution of Jerboa, So you can try reproduce it and then do the command, or try to find it in adb shell logcat (GL tho). You can also try `adb shell "timeout 5s logcat | sed -En 's/.*proc ([0-9]*):com.jerboa.*/\1/p'` which should print all PIDs of Jerboa executions and then try `adb shell logcat *:V --pid <PID>` And see which one prints all the relevant information. 

Without i can only speculate and say that it was the same bug as the previous I mentioned and the reply is weird though. That should have still worked because we do store the JWT and that's the only thing it needed. It could also be that your instance is having issues, the reason why it keeps failing on retrieving the relevant info at startup. And the reason reply gets stuck?

**Comment by Vuks69** [comment]
Same issue. Logging in let's me see my profile, but not comment. Viewing inbox shows me the red "not_logged_in" message. I'll try to get the logs tomorrow.

**Comment by MV-GH** [comment]
Thanks, note though that if you restart your device/ launch jerboa in the mean time you are gonna have a harder time getting the logs
