### ISSUE TITLE
French text in the nav bar is broken

### ISSUE THREAD

**Issue by Richardsause** [dessalines/jerboa#1180]
### Jerboa Version

0.0.44

### Android Version + Phone

Lineage OS 20(Android 13) Moto edge 20

### Describe The Bug

![IMG_20230815_101315](https://github.com/dessalines/jerboa/assets/89277764/17371978-c2f2-48cc-a741-29cec326dd24)

### To Reproduce

1. Be French
2. Install jerboa
3. Realize you speak the wrong language

**Comment by MV-GH** [comment]
Whats it supposed to do in these cases?

**Comment by Richardsause** [comment]
> Whats it supposed to do in these cases?


![IMG_20230815_101315](https://github.com/dessalines/jerboa/assets/89277764/4cf83906-20cc-4c3c-a9b4-15fe0e66ff6a)

this is what it looks like in english for instance, as you can see there are no cut-up words, strangely misaligned or misplaced text

**Comment by twizmwazin** [comment]
The way we have solved this issue in other translations is to find shorter translations where possible. Could a native French speaker suggest shorter translations, if any exist?

**Comment by Baliverbes** [comment]
> The way we have solved this issue in other translations is to find shorter translations where possible. Could a native French speaker suggest shorter translations, if any exist?

_Chercher_ instead of _Rechercher_
_Rechercher_ in this context means "to search thoroughly". _Chercher_ is somewhat less common in the internet space, but close enough imho, and it is used in places already (I have not done an inventory)

_Sauvé_  instead of _Enregistrés_
Without an S as to make it innumerable (personal preference, works with or without). Used to be the most common translation for 'save file' in most programs, perhaps less common nowadays. Transliteration of the english "saved".

**Comment by MV-GH** [comment]
Do you prefer the old text? I made it smaller and the old text fits now

![263487812-820f09ad-5bff-4226-98f3-7d0986567e8a](https://github.com/dessalines/jerboa/assets/67873169/39b8a8e6-d870-468c-a6c7-69640e813aa4)

**Comment by FLamorce** [comment]
Yes, old text with smaller font is perfect 👍🏻
