### ISSUE TITLE
Scaled sort not shown for `v0.19` instances

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#1293]
### Jerboa Version

0.0.53

### Android Version + Phone

Android 13

### Describe The Bug

The scaled sort option is not shown when logged into `v0.19` instances.

### To Reproduce

See above

### In the case of a crash or when relevant include the logs

NA

**Comment by MV-GH** [comment]
![image](https://github.com/dessalines/jerboa/assets/67873169/43ee4f30-3df0-4a45-a1f7-4ed8044d8c00)

Those instances at the time where 0.19.0-rc.X, Those are below 0.19.0, thus these sort types weren't shown.

Now since Lemmy is 0.19.0 it is shown :)

I will fix it though that it will ignore preleease tags.

**Comment by dessalines** [comment]
Fixed by #1295
