### ISSUE TITLE
Open links of posts and communities in app

### ISSUE THREAD

**Issue by PassionateG1t** [dessalines/jerboa#186]
Right now when someone links another post or a community, it redirects to the web. The ability to open them in the app itself would be useful.

**Comment by EdoSecco** [comment]
This should be implemented in the app system settings, but with the possibility to add custom URLs, let's say for every single Lemmy instance.
Alternatively - and that would be way better - it could be done via app updates, updating time by time the list of instances and adding the related URLs to the list.

**Comment by dessalines** [comment]
Agree, this would be useful to have. But this requires a [hardcoded list of URLs](https://developer.android.com/training/app-links#android-app-links), so I would probably only add these for the most popular instances, and any others on request.

**Comment by dessalines** [comment]
These do appear to be working.

**Comment by EdoSecco** [comment]
If I try to open https://feddit.it/post/75565 the app goes to https://lemmy.ml/post/75565
Same for groups, https://lemmygrad.ml/c/starwars > https://lemmy.ml/c/starwars

Should I check something in order to have it working in the right way?

**Comment by dessalines** [comment]
It can't use the right link unless your jerboa account is that server currently. I might be able to rework this but it'll pry be a while.

**Comment by 0hCome0n** [comment]
I get the feeling constantly adding hardcoded instances to the deeplink support is going to get annoying, and yet as a user I would like to keep all my activity inside the app.

I've got the following instance requests

midwest.social
mander.xyz
slrpnk.net
lemmy.ca

Thanks!

I'm going to put in a feature request with the Android dev team to let the user add custom URLs inside the system settings.

**Comment by dessalines** [comment]
It is definitely annoying. I think the way I'm going to handle it, is like other federated apps: just let the search box allow you to paste in urls, so you can view its representation in the app. Because this has been a mess to get working and maintain.

**Comment by Dakkaron** [comment]
I'd like to have the option to open these links directly in the app without going through the system. Since Android 12 crippled the "open with" dialogue, it's hardly usable at all.

But since these internal links tend to follow their own link scheme, it shouldn't be too hard to not render them as a link that goes through the system, but instead opens directly in the app.

Maybe make this toggleable, but I am pretty sure there aren't many people who want to switch to the browser when they press a link to a Lemmy community inside Jerboa. I'm in the app already, so obviously I want to use the app.

**Comment by twizmwazin** [comment]
Closing in favor of #524
