### ISSUE TITLE
Allow setting a different font size for comments

### ISSUE THREAD

**Issue by Elbullazul** [dessalines/jerboa#373]
The default 16px font size is OK for most of the UI, but comments have almost double the font size. Would it be possible to change font size only for the comments?

**Comment by Elbullazul** [comment]
Here's an example:
![Screenshot_20230602-161146](https://github.com/dessalines/jerboa/assets/15310985/7c8efc62-6c9e-4659-a8b5-a9692a425a15)

The community font size is pretty small, and even the post title is smaller than the comment font size

**Comment by Nisker** [comment]
I have the same problem. 
I think this is a bug we are experiencing.
From what i can tell, it's due to the comments not "reacting" to the android font setting, while the rest of the UI does.
I use the smallest font size on Android, which makes this a lot worse.
@Elbullazul what font size you use in your Android settings?

**Comment by Tavius02** [comment]
I have the same issue with app, and I use the second smallest font size.

**Comment by dessalines** [comment]
This has to do with the markdown renderer jerboa is using, not really working great with jetpack-compose sizing, but also being the only one that handles images properly. 

I *had* a PR out to replace it with a better one, but images don't work well on that one. 

Rather than having a  custom font size just to support that older library, I'd rather just get the new one working properly.

**Comment by jplsek** [comment]
> Hrm. I noticed the comments are a _bit_ small right now, but I suppose with the new markwon, its using `bodyLarge`. Perhaps all we need to change is that. We also need to verify that its actually using that: there's a chance its getting ignored.
> 
> I'd definitely prefer just a single font size, so that all titles, bodies, etc can scale accordingly. Otherwise it could get complicated very quickly.

I might be missing some context, or maybe there is a bug somewhere, but for me when testing on `main`, the comments look larger to me, not smaller.

Before (comparing against the home activity):

| | |
|---|---|
| ![Screenshot_20230610_151546](https://github.com/dessalines/jerboa/assets/2388657/d3958b73-a959-4c7e-98fa-0f5b420cc015) | ![Screenshot_20230610_151616](https://github.com/dessalines/jerboa/assets/2388657/adf51ece-1e8c-4b6b-b400-781e35209a4d) | 

After [(setting to Medium)](https://github.com/dessalines/jerboa/commit/23c0fee1a69c858e7c3582bc8a415e140c96ff75), such that the sizes looks consistent:

| | |
|---|---|
|  ![Screenshot_20230610_151546](https://github.com/dessalines/jerboa/assets/2388657/d3958b73-a959-4c7e-98fa-0f5b420cc015)  |  ![Screenshot_20230610_151657](https://github.com/dessalines/jerboa/assets/2388657/0cc1ad13-9000-4114-9970-2781249872ad) |

(I'm also here because I felt that the comment font size is too large, and changing font size from the app settings would then make the home activity page font size too small)

**Comment by dessalines** [comment]
I looked at this code again, and the markdown view should use the correct fontSize now.
