### ISSUE TITLE
Allow voting on posts in list view

### ISSUE THREAD

**Issue by Anna-log7** [dessalines/jerboa#394]
Currently if you are using the "List" Post view, you can't vote on posts unless you click into them, which you can do in the card styles

- Add up and down vote controls in the List view

**Comment by dessalines** [comment]
These come from boost, which also doesn't have voting in list view. I'd be open to this, but I don't know where the buttons would go.

**Comment by maltfield** [comment]
Let's not clutter the list view please. Users who choose the list view choose it because **they *want* a compact view**. There's no reason to add additional icons to the most compact view when those actions could be triggered by [swipe left and right](https://github.com/dessalines/jerboa/issues/52#issuecomment-1586247868).

**Comment by twizmwazin** [comment]
This was implemented in #472, with an option to disable it if you don't want it.
