### ISSUE TITLE
Release on f-droid

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#41]

**Comment by IzzySoft** [comment]
Coming :smile: Tomorrow [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.jerboa) (with the next sync at around 19:00 UTC) – F-Droid when you feel ready for it. Meanwhile, could you please check if you've got the correct APK attached to tag 0.0.4 – because the one there identifies as 0.0.3? Thanks!

**Comment by dessalines** [comment]
Sweet thx @IzzySoft ! I'll re-upload that one shortly. Also don't I have to set up a metadata and fastlane folder and all that?

**Comment by IzzySoft** [comment]
For F-Droid, Fastlane is highly recommended, yes. For my repo, it's highly welcome as well; if not available, I create it locally. You can take a look at the listing when your app shows up there tonight; if you like what you see, I can provide you with the "initial fastlane package" via a PR, and you can then build on that. It's not much, though, but rather a simple "starter package"…

**Comment by dessalines** [comment]
That'd work!

**Comment by IzzySoft** [comment]
OK, there you go :smiley: Feel free to replace what you think needs replacing. As pointed out, it's rather a quick-start skeleton. I've linked you to my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) which might prove helpful. As for formatting the `full_description.txt`, experiences collected [here in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) might be useful as well.

Oh, I see Jerboa is just going online now: the index was just pushed. Database refresh in about 20min, then it should be visible on the website (for the client, just add my repo or if it's already there, refresh).

**Comment by dessalines** [comment]
Nice! This is just in your izzy fdroid repo now, correct? What should I do next for it to get pushed to the main f-droid repo?

**Comment by IzzySoft** [comment]
Yes, for now it's only in my repo (which is often used to "let things grow" until they are "mature enough" for the wider public).

If you feel ready for F-Droid.org, you could open a [Request For Packaging](https://gitlab.com/fdroid/rfp/-/issues), so you get first results from the issue bot which takes a deeper look into the code, to find out if there are any potential issues. I could then provide you with the "upper half" of the metadata YAML file (the part used in my repo, once more) and we complete it for a merge request at fdroiddata, to finally get the app listed. It seems to be "plain Kotlin", so that shouldn't be too hard (I'd even dare trying the packaging then).

Once your app is listed there, I'd usually give it a short overlap (10 days or so) before removing it from my repo again – unless you want it to stay there for some reason. See e.g. my [FAQ](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some background. One such reason could e.g. be that you have two different kind of tags, and the stable releases go to F-Droid while my repo only takes the testing versions, so your testers and "early adopters" can easily stay up-to-date.

**Comment by dessalines** [comment]
Mmmk  that's submitted: https://gitlab.com/fdroid/rfp/-/issues/1998

**Comment by IzzySoft** [comment]
Thanks! Just saw it (as a maintainer, I subscribed to get noticed about all activity there :wink:). Let's wait for the bot again, then we can continue to the MR (as we just did with the other app).

**Comment by IzzySoft** [comment]
Congrats to the successful inclusion! Just as a note: I'll remove Jerboa from my repo after around 2022-02-11 (giving it 10 days overlap) – unless you want me to keep it there as well for some reason ([see here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some background). So if you want me to keep it, please speak up before that date :wink:

**Comment by dessalines** [comment]
Thx! 

> I'll remove Jerboa from my repo after around 2022-02-11 (giving it 10 days overlap) – unless you want me to keep it there as well for some reason ([see here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some background).

Nah that's okay, feel free to remove it from izzy.

BTW I just did another release / tag, how long does it usually take for f-droid to pick it up, and is there anyway to see its progress?

**Comment by IzzySoft** [comment]
For F-Droid: [How long does it take for my app to show up on website and client?](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client) (TL;DR: usually around 4 days) For my repo: usually less than 24h (unless you release less than once a year, then the update-check is set to weekly). The difference is that my updater just picks the APK you've built – while F-Droid needs to build everything from source itself, which is additional effort.
