### ISSUE TITLE
Long press action on comments to vote

### ISSUE THREAD

**Issue by a1studmuffin** [dessalines/jerboa#418]
As per https://github.com/dessalines/jerboa/pull/398#discussion_r1216871493, once we can tap a comment header/body to toggle expanding it, this frees up the long tap action on these elements for voting.

One thought I had on this - should we collapse the comment footer (the row containing upvote/downvote buttons etc.) by default on all comments, and the user has to long press the comment to reveal the footer, so the user can upvote/downvote? That's how BaconReader works and it means we can fit a lot more comments on-screen by default.

**Comment by dessalines** [comment]
I would like that to be a setting, possibly collapsed by default. I def prefer having the buttons shown, at least while we don't have long-press voting.

**Comment by Brendan-D15** [comment]
> I would like that to be a setting, possibly collapsed by default. I def prefer having the buttons shown, at least while we don't have long-press voting.

This is how Joey handles it. And I would prefer it this way as well.

**Comment by a1studmuffin** [comment]
Nice, sounds like a setting will give most people what they prefer.

**Comment by 0hCome0n** [comment]
Person who didn't see this until the change was implemented. Long-press on the body of the comment means the text can no longer be highlighted in order to copy parts of it or to bring up extra options for dealing with links.

At the very least I would like a toggle in the settings to turn this function off, but this extra feature is getting in the way that I normally interact with the app.

Perhaps you could move the long-press function to the header of the comment so that short press closes the entire comment and long press closes just the action bar?

Or I'll just learn to live with it. I'm just a guy complaining on the internet.

**Comment by Brendan-D15** [comment]
> Person who didn't see this until the change was implemented. Long-press on the body of the comment means the text can no longer be highlighted in order to copy parts of it or to bring up extra options for dealing with links.

One of the ways to handle this would be to add some sort of ellipses icon/option when you long press. Clicking on that would open up additional choices where one of them could allow you to copy/copy all.

The other way to handle this could be as you said which is to move this action to only affect the header of the comment.

**Comment by Landrin201** [comment]
I'd like to add my two cents here

In both Slide for Reddit and Infinity for Reddit, there were two main interactions with comments: A  single tap, and a long press.

By default, the single tap shrank the comment, and the long tap opened up the comment interactions (vote, reply, report, etc.). But there was a toggle in the settings that let you switch the long tap and single press actions.

I like the idea of having these actions be customizable through the settings. IMO any changes that get made to them should be preceded by the ability to customize them in the settings, so that everyone doesn't get locked into one thing.

**Comment by dessalines** [comment]
We have swipe actions now.
