### ISSUE TITLE
Fix markdown rendering issues, with font size and images. 

### ISSUE THREAD

**Issue by dessalines** [dessalines/jerboa#440]
Realized we don't have an issue for this yet, even though ppl are contributing PRs like #432 .

The main alternative to `jeziellago:compose-markdown`, is likely https://github.com/halilozercan/compose-richtext . But last time I tried this, it didn't support images well.

**Comment by oscarnylander** [comment]
It might be viable to upstream some image support/image fixes.

**Comment by awdsns** [comment]
Don't know if this should be in this issue or a separate one, but in general the markdown rendering in Jerboa is not up to par:
https://aussie.zone/post/3604

![grafik](https://github.com/dessalines/jerboa/assets/136314294/76e6adab-b43a-42b3-a2bc-dd5ebf95c287)


The web UI and apparently also mlem on iOS seem to support all this.

**Comment by awdsns** [comment]
Another thing that's been bugging me to hell (not new though AFAIK) is that most numbers (>1 digit) are turned into clickable `tel:` links (phone numbers).

**Comment by trubeck** [comment]
I don't know if this is fixed with the new renderer, but besides spoilers, strike-through text does not work for me. In addition to that, there doesn't seem to be any rendering of Markdown in the overview cards, which is especially bad for spoilers. If you want me to create a separate issue for this, I'm happy to do so.

This is my post on Lemmy regarding this issue: [](https://feddit.de/post/814396)

**Comment by bappitybup** [comment]
is it intentional that markdown doesn't apply if the start and end of it are on new lines?
![image](https://github.com/dessalines/jerboa/assets/12457072/5758f0fd-0ddd-4157-97ce-fb3318ea58ac)

**Comment by twizmwazin** [comment]
I'm going to mark this as complete because the original issue has been fixed. If there's a specific markdown feature that we should support that isn't supported, please open a new issue specific to that missing feature.
