### ISSUE TITLE
Crash on opening specific link

### ISSUE THREAD

**Issue by helpimnotdrowning** [dessalines/jerboa#556]
** Jerboa Version **
0.0.33

**Describe the bug**
In this post to c/Anime@lemmy.ml : https://feddit.de/post/761086 , clicking on the markdown-styled link in the first paragraph to c/japanesemusic@feddit.de crashes the app.

I haven't seen any other links that also do this, but I will update if I find anything.

**To Reproduce**

1. Go to https://feddit.de/post/761086
2. Click on the link in the 1st paragraph 
3. App crashes

Using:
* LG v60 (root)
* Android 11
* Jerboa 0.0.33 via Play Store
* My user host: lemmy.sdf.org

**Comment by awdsns** [comment]
Woohoo I broke the app!

So this link is a relative one (no protocol or host part, only `/c/japanesemusic@feddit.de`) which AFAIK is currently the only way to do sort-of portable links to communities. At least this works with the web UI.

FWIW for me Jerboa opens Chrome with the link, which then obviously doesn't work because of the missing host.

In general it would be nice if Jerboa (and other frontends) could just natively convert `!community@instance` into links by itself, then such hacks wouldn't be necessary.

**Comment by awdsns** [comment]
Related: #454

**Comment by awdsns** [comment]
Nevermind, for me it crashes too with 0.0.33 from Play Store. I think it was with a previous version that those links opened in Chrome.

@Anna-log7 might this be related to #413?

**Comment by awdsns** [comment]
But would that community name `name@instance@instance` cause the app to crash?

I can't install Android Studio to debug it right now and zero experience with Jetpack Compose, but if you have a link target of *only* `/c/somecommunity@someinstance`, could that still match on the `uriPattern = "{instance}/c/{name}"` and cause the null check on `instance` to blow up?

https://github.com/dessalines/jerboa/blob/e4923c9308ba618ef80a0aa31c5fb8c411d9987d/app/src/main/java/com/jerboa/MainActivity.kt#L207

**Comment by beatgammit** [comment]
Ok, this should behave a lot better now, please retest.

**Comment by twizmwazin** [comment]
Given the lack of updated info and the number of changes that have happened surrounding link handling, I'm going to mark this one as complete.
