### ISSUE TITLE
Get Karma Displayed on the Profile

### ISSUE THREAD

**Issue by WreckingBANG2** [dessalines/jerboa#557]
- [YES] Did you check to see if this issue already exists?
- [YES] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [YES] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

Is it possible / planned to get the Karma displayed on the ProfilePage? 
The API would allow it.

**Comment by MV-GH** [comment]
I don't think the API supports it see https://github.com/LemmyNet/lemmy/issues/2370#issuecomment-1196642040

**Comment by dessalines** [comment]
We do actually have these in the API, but are against showing them in any client. They promote karma farming and are psychologically harmful.

**Comment by WreckingBANG** [comment]
Oh. Ok. Your right.

**Comment by L3v3L** [comment]
I agree karma farming being psychologically harmful. With that in mind just a thought, if you think knowing someone has a negative karma is somehow informative, maybe instead of showing the actual value, maybe just display an icon if in the negative. I'm not sure on the social use of this, maybe best to think of the repercussions before hand.
