### ISSUE TITLE
Posting comment fails

### ISSUE THREAD

**Issue by tonydiep** [dessalines/jerboa#694]
Error message is language not allowed.
Failed twice on two separate servers.
Worked on third time.
Intermittent.

**Comment by EuphoricPenguin** [comment]
I'm having a similar issue. It seems to be related to Interface Language, but it does seem to be inconsistent like you mentioned.

**Comment by tonydiep** [comment]
![Screenshot_20230616-213303](https://github.com/dessalines/jerboa/assets/705269/3a7b5345-f5aa-4a2a-b3d3-d1092899129b)

**Comment by tonydiep** [comment]
I notice when posting to Lemmy using web interface there's a combo box for language.

I don't see the equivalent in the app.

Could it be that the app is not setting language when posting and some servers have a default language it falls back on and others do not?

**Comment by EuphoricPenguin** [comment]
Yeah, that could be it. There's an option for admins of each instance to choose an instance language; if they don't configure that properly, it could throw a wrench into things.

**Comment by tonydiep** [comment]
As a quick fix can we send a safe default like us-en ?

I don't know the code well enough to submit a pull request or I would do it myself.

- Tony Diep (He/Him)
________________________________

**Comment by ZJouba** [comment]
@MV-GH I see the language for a comment is nullable
`val language_id: LanguageId? = null`
Shall I use the language set in LookAndFeel as the default for a comment?

**Comment by MV-GH** [comment]
I don't know the inner workings of Lemmy enough to know the full consequences of setting that field. I assume null would always allow? Since it seems to be intermittently work maybe that sounds more like a Lemmy issue. Either way I would avoid setting that field until we have a option implemented that allows you to set the language per comment (by default uses that langague_id). Because the doing the above, you would assume that all comments written by the user would be in that language.

@dessalines can you shed some light here?

**Comment by MV-GH** [comment]
https://github.com/LemmyNet/lemmy/issues/3451 Closing this as this way a bug in Lemmy 0.18.2
