### ISSUE TITLE
Constant "Login first" message, regardless of login.

### ISSUE THREAD

**Issue by oliversalzburg** [dessalines/jerboa#740]
**Jerboa Version**
0.0.33

**Describe the bug**
When I try to vote on a post, I get a popup saying "Login first", even though I have already logged in. I can log out and back in as many times as I want, the behavior stays consistent.

I also can not perform any other actions that require authentication. My subscriptions and profile picture are shown on the sidebar though.

**To Reproduce**
This only started happening after I increased the complexity of my password. It contains `&`, `[`, `]`, `^`, which I would all consider likely candidates of messing with the login.

**Comment by MV-GH** [comment]
I do not think the complexity of your password is relevant here  to reproduce the error. I have similar symbols and I'm not experiencing this. This is most likely caused by something else.

**Comment by oliversalzburg** [comment]
Good point, it was just the last thing I changed. Happy to look into other possible causes, but couldn't find the root cause so far.

**Comment by PennyJim** [comment]
Can confirm I experience it too. No clue what's causing it and I'm not fully dropping Reddit until my Reddit app stops working. So I'm not putting all my energy into figuring it out.

I did try clearing the storage because I thought my 'second account' that was just the same one but with an incorrect password was the issue, but I've still experienced it.


Coming back to this draft, I only experienced it once after that and then restarted Jerboa and I haven't had any issues since.

**Comment by oliversalzburg** [comment]
For me, the issue persists, but I also didn't have time yet to troubleshoot this. Maybe the HTTP-based communication in Lemmy 0.18 will make this easier.

**Comment by AndrewG2** [comment]
I have this issue appear with multiple accounts.  On 2nd account login failure due to the lemmy instance being on 17 instead of 18, both accounts are "forgotten" from the app and require login again.

**Comment by oliversalzburg** [comment]
After the 0.18 update, I was able to inspect the HTTP traffic for login requests more easily. My email address was not verified on one address (I thought it was). I don't remember what it was on the other instance. Problem is resolved now though 👍
