### ISSUE TITLE
"Default View" preferences won't hold

### ISSUE THREAD

**Issue by Snapz54** [dessalines/jerboa#758]
**Jerboa Version**
0.0.33 (on SM-N950U running Android 9)

**Describe the bug**
Save default view to "All" and "top day". "All" persists correctly and as expected, but "top day" keeps resetting to "old" after existing a selected thread.

**To Reproduce**

1. Set default view
2. Scroll view
3. Select thread
4. Back out
5. Error should be ppresen

**Comment by yuchen071** [comment]
I don't run into the bug with your reproduction method, but I do run into it with different reproduction methods:

**To Reproduce**  

1.  Have 2 or more accounts
2. Set default view to "TopDay"
3. Switch accounts and back
4. Homepage should be "Old" now.

The same issue also happens when you set it to other options, namely: 
-  TopDay becomes Old
-  TopWeek becomes TopDay
- TopMonth becomes TopWeek
- TopAllYear becomes TopMonth
- Most Comments become TopAllYear

Active, Hot, and New are unaffected, however.

**Comment by BraveSentry** [comment]
I encountered a similar bug running Version 0.0.33 on Android 12. I set my prefs to All/New, but they go to Local/Active whenever the screen turns to landscape or to portrait, or when I bring the app back to the front after having opened another one.

**Comment by MV-GH** [comment]
I think that one got fixed already

**Comment by BraveSentry** [comment]
Just downloaded 0.0.34-alpha and you are right, it is fixed. I don't know about the others but as for me, this issue could be closed.
