### ISSUE TITLE
Nightly/Weekly builds

### ISSUE THREAD

**Issue by beatgammit** [dessalines/jerboa#797]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/jerboa

** Describe the feature request below **

I've seen interest in users helping test prerelease builds, and asking them to build from source seems to be a bit much.
 
Some things I think we'd need are:

- different name and icon
- clear database if there's a migration issue
- build date in about section
- links to these builds somewhere on GitHub
- Google Play beta program?

**Comment by MV-GH** [comment]
Let me reiterate my suggestions:

> different name and icon

Name: Jerboa (NIGHTLY) icon: black version of current icon

> clear database if there's a migration issue
Set allowBackup to false in manifest, should solve this issue

> build date in about section
We would probably get this date through an ENV variable
and this should only show for the nightly build,
possibly this build should use a different app suffix like `.nightly`
And then to detect if this build is running nightly from within the code we can just check the applicationId

>links to these builds somewhere on GitHub
The pipeline could make preleases with the builds


I dont think a weekly is needed as we will probably have a weekly release.
Also if we dont have a change that day it shouldnt make a nightly build.

**Comment by dessalines** [comment]
> I dont think a weekly is needed as we will probably have a weekly release.

Yep, I definitely plan on doing releases ~ once a week.

The difficulties here are ensuring that the entire process gets automated. Woodpecker can do cron jobs, and it already can do release builds... the issue is where to put those, and how to make them easy to upgrade for beta testers.

**Comment by WMarks-Enertech** [comment]
Since we seem to be against using Github Actions because "proprietary" and "M$FT bad", there is a plugin for woodpecker->GitHub releases, see: https://github.com/woodpecker-ci/plugin-github-release


I think adding a small "nightly build" or whatever into the README isn't a huge difficulty. We can have a specific "release" on Github called nightly that has its artifacts replaced by the daily build. Or just add a new artifact to the release every night, with dated filenames for the apk.

We could also use the plugin to generate the Releases we currently have. No need for someone to be building them on the PC and uploading them to Github manually...
