### ISSUE TITLE
Reaching bottom of loaded posts sometimes doesn't load more

### ISSUE THREAD

**Issue by bappitybup** [dessalines/jerboa#806]
**Jerboa Version**
0.0.34

**Describe the bug**
sometimes when reaching the bottom of the main feed loaded posts, no more posts will load until you scroll a little bit up and then back down to the bottom.

I'm not exactly sure what's causing it so it may take a couple times reaching the bottom of the feed for the issue to appear, try scrolling down very fast.

**To Reproduce**
I think this could be caused by a timeout when trying to grab posts, try these steps on an overloaded instance to force a timeout

1. Scroll down on main feed to last loaded post until hitting bottom
2. If more posts load, scroll down to the next bottom of the feed
4. Scroll back up at least 2 posts on the feed
5. Scroll back down to the bottom of the feed (new posts should load)

**Comment by MV-GH** [comment]
And is this consistent? Because i can't reproduce this. I did however had before when i scrolled down no new posts appeared. And that is normal it got a timeout from the server. We should handle this timeout better.

**Comment by bappitybup** [comment]
> And is this consistent? Because i can't reproduce this. I did however had before when i scrolled down no new posts appeared. And that is normal it got a timeout from the server. We should handle this timeout better.

Sorry it's poorly worded, intermittent but from what you said I assume if it times out then when you're already at the bottom of the page it won't try to grab posts again

**Comment by TheRedSpy15** [comment]
I experience this pretty regularly myself. As the issue creator stated, scrolling up a little and back down fixes it

**Comment by M0Z1NG0** [comment]
This issue seems to have been made worse in one of the recent updates. You can no longer scroll back up a little, then back down to force more posts to load. Instead the feed just ends and the only way to see more posts is to refresh and start scrolling again from the top.

**Comment by MV-GH** [comment]
Hmm, it should have kept the existing behaviour. I will look into it. #809 Corrected some issue such as when loading new pages fails it would then skip that page on next retry

**Comment by M0Z1NG0** [comment]
@MV-GH My bad, I tested in other instances and edited my post for clarification. I am currently using the 0.38 alpha.

**Comment by MV-GH** [comment]
But this behaviour did exist before 0.38?

**Comment by M0Z1NG0** [comment]
Okay, I rolled back to test. 0.0.34 crashes on launch, but 0.0.35-0.0.38 all behave the same. Here's some more info:

Once the user scrolls to the bottom of the feed, more posts will start to load, but if the user scrolls down again during this load, the user will no longer be able to scroll down until first scrolling up. After that, the screen will continue to scroll as normal. If the user doesn't scroll during the load, then the user will also be able to scroll as usual once they load in.

It seems when instances are particularly busy, like the last couple days, sometimes posts will not be loaded once the user reaches the bottom of the feed, and it can take up to 30s+ for the posts to start loading. There's no loading bar or error popup, so no indication anything is happening until suddenly posts start to load in and at that point it behaves as described above.

So I'm pretty sure all this behavior has been the same since at least 0.0.34, it's just now more exposed due to the recent surge in sign ups. Might be worth adding a loading bar or error message when the posts are taking longer than normal to load.

**Comment by MV-GH** [comment]
Alright thanks for the investigating.
