### ISSUE TITLE
Parent comment navigation buttons block bottom of comments

### ISSUE THREAD

**Issue by anonderpling** [dessalines/jerboa#883]
On acting to the bottom of a page on my tablet, I can't use the toolbox for the last comment (to vote or reply), as it's covered by the up/down vote icons for the main post. [Screenshot](https://github.com/dessalines/jerboa/assets/125647602/14b43871-9641-49ab-aac2-f230d578ef63)

**Comment by twizmwazin** [comment]
I've edited your issue down to just point 1, in the future please make separate issues for each item. Regarding 2, that will be fixed when #817 is merged. For 3, draft support is being worked on in #844 which should mitigate that. I don't think the bottom nav would work well in the comments and community views because they don't really correspond to any of the bottom nav elements.

**Comment by yate** [comment]
@anonderpling What's your tablet model and Android version? I wasn't able to reproduce this in an emulator

**Comment by dessalines** [comment]
Stale, can't repro.
