### ISSUE TITLE
Filters are different in server & local database.

### ISSUE THREAD

**Issue by nahwneeth** [dessalines/jerboa#886]
**Jerboa Version**
Jerboa v0.0.35-alpha

**Android version + phone**
Android 13

**Describe the bug**
When changing the account settings, the local db gets updated even when saving the settings to the server failed. Therefore there is a lot of discrepancy in the filters based on where the default filters are read from. They will remain unchanged if the request uses the defaults returned from the site response. But will use the updated defaults if read from the local db or account variable.

**To Reproduce**
- Change default sort & listing filter in account settings.
- Save settings and bug surfaces when the network call fails.

Please include the logs.
I added a line to to log the failure message. Seems like email is required to save the settings.
```
jerboa save settings    com.jerboa.debug                     E  java.lang.Exception: email_required
```

Due to the captcha issue, many servers have taken resort to email verification. This explains why the bug surfaced in Jerboa v0.0.35-alpha although not much change was done to this part of the app compared to the previous version.

**Comment by MV-GH** [comment]
Since #817 does it now always read from local DB or always from the lemmy account? There is always gonna be possibilities for discrepancies between local db and lemmy account settings. Since lemmy acount settings can be updated from any client. We should just handle this better. The lemmy acount settings should override the local db settings. And the local settings should only really be used for when you are  in anonymous mode

**Comment by nahwneeth** [comment]
The local db for all the requests. The settings page displays the defaults from the lemmy account, so the defaults displayed on the settings page and the ones used for requests might not be the same. I'm currently working on a PR which overrides the local db based on the defaults that were obtained when loading the site.

**Comment by MV-GH** [comment]
Alright sounds good 👍
