### ISSUE TITLE
Default sort and listing type cannot be overridden 

### ISSUE THREAD

**Issue by swmarks** [dessalines/jerboa#887]
**Jerboa Version**
0.0.36

**Android version + phone**
Android 13 + Samsung Galaxy Fold 4

**Describe the bug**
Jerboa now respects the sort order and listing type as defined in your Lemmy user settings for the defaults, but if a logged in user tries to change the sort order and listing type on the home tab, it automatically changes back to the default and refreshes. I believe this may have been caused by committing this PR: https://github.com/dessalines/jerboa/pull/854

**To Reproduce**

1. Make sure you're logged in as any user
2. Go to the home tab
3. Attempt to change either the sort or listing order
4. Observe behavior described above

**Comment by rammjet** [comment]
I believe that this is why if I  tap "All", I still set to "Local".

**Comment by silentTeee** [comment]
Yup I am seeing this as well. I am not sure yet but at first glance it almost seems like a race condition?

**Comment by vnckppl** [comment]
Also, the checkbox options are not stored when hitting 'save settings' (e.g., 'Show Notifications for New Posts').

**Comment by nahwneeth** [comment]
In #817, I pushed a temporary fix where the defaults are read from the local db. The problem lies in the account settings where it continues to update the local db even though updating the server failed. So rn, the defaults might not sync with the server and therefore will not carry over if you use a new device or if you log out and log in. You can see it in the settings page itself where the defaults will still be Local & Active (or whatever the sever defaults were when you logged in).

This should ideally be taken up with #840.
